# Scikit-learn

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("../data/Advertising.csv", index_col=0)
df.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [6]:
number_of_samples, number_of_features = df.shape[0], df.shape[1]-1  #-1 because Sales is a label, not a feature.

number_of_samples, number_of_features


(200, 3)

In [7]:
X, y = df.drop("Sales", axis="columns"), df["Sales"] # drop kollar på rader, men vi tvingar den till att kolla på kolonner.
X.head()

TV  Radio  Newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [10]:
y.head()

1    22.1
2    10.4
3     9.3
4    18.5
5    12.9
Name: Sales, dtype: float64

## Sklearn - typical steps


1. train|test split, sometimes train|val|test split
2. scaling sometimes required (typ som z transformering)
    - min-max scaling
    - standardization
    - ...
    - scale the training data, 
    - scale test data to the training data --> avoiding data leakage
3. Fit algorithm to training data - model training
4. Predict test data (sometimes called transform/förvandla)
5. Evaluate

## Train|test split

In [13]:
from sklearn.model_selection import train_test_split

#help(train_test_split)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((140, 3), (60, 3), (140,), (60,))

## Feature scaling

Normalization (min- max feature scaling)
- $X' = \frac{X-X_{\min}}{X_{max}-X_{min}}$

tar vår data, subtraherar bort med det minsta,  dividerar med vår största data subtraherar bort vårt minsta?

Vi får ut en matris


Feature standardization
- $X' = \frac{X -\mu}{\sigma}$

In [17]:
from sklearn.preprocessing import MinMaxScaler # preprocessing, saker vi gör innan. typ städar datan, croppar bilder

# instantiate a scaler instance(object)
scaler = MinMaxScaler()
scaler.fit(X_train) # important - use this for training data

scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min()=}")
print(f"{scaled_X_train.max()=}")
print(f"{scaled_X_test.min()=}")
print(f"{scaled_X_test.max()=}")
# note scaled_X_test min != 0, scaled_X_test.max != !

# 0 <= scaled_X_test <= 1
# 0.005964214711729622 <= scaled_X_train <= 1.1302186878727631


# värden för train.min och train.max är mellan 0 och 1
# värden för test.min och test.max är mellan 0.0059... och 1.130...

scaled_X_train.min()=0.0
scaled_X_train.max()=1.0
scaled_X_test.min()=0.005964214711729622
scaled_X_test.max()=1.1302186878727631


In [20]:
scaled_X_train.shape, scaled_X_test.shape

((140, 3), (60, 3))

## Linear regression

### Ordinary least squares

In [26]:
from sklearn.linear_model import LinearRegression

model_OLS = LinearRegression()
model_OLS.fit(scaled_X_train, y_train) # fit on training data
print(f"Parameters {model_OLS.coef_}") # beta1, beta2, beta3. skalad data, därför skiljer den sig från tidigare. måste alltid predicta på skalad data.
print(f"Intercept {model_OLS.intercept_}") #beta0

Parameters [13.02832938  9.88465985  0.69237469]
Intercept 2.7418553248528124


### Stochastic gradient descent

In [30]:
from sklearn.linear_model import SGDRegressor 

model_SGD = SGDRegressor(loss="squared_error", max_iter=10000)
model_SGD.fit(scaled_X_train, y_train)
print(f"Parameters {model_SGD.coef_}") # beta1, beta2, beta3. skalad data, därför skiljer den sig från tidigare. måste alltid predicta på skalad data.
print(f"Intercept {model_SGD.intercept_}") #beta0

Parameters [11.96697312  9.01619537  1.32450143]
Intercept [3.56978239]


## Manual prediction

In [37]:
test_sample_features = scaled_X_test[0].reshape(1,-1) # vi fick error av models_OLS.predict(test_sample_features). lösning; .reshape(1,-1)
test_sample_label = y_test.values[0]
test_sample_features, test_sample_label

(array([[0.54988164, 0.63709677, 0.52286282]]), 16.9)

In [39]:
test_sample_features.shape

(1, 3)

In [50]:
model_OLS.predict(test_sample_features)[0]

16.56539629743484

In [48]:
model_SGD.predict(test_sample_features)[0]
# vår modell säger att ifall vi lägger 163.3k på advertising av tv, så kommer vi sälja 16.586922696530692k units av TV, 
# enligt denna modell och sample vi har använt för denna modellen.

16.586922696530692

In [33]:
X_test.iloc[0].to_numpy()

array([163.3,  31.6,  52.9])

## Evaluation

In [53]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 1. predict on test data
y_pred_OLS = model_OLS.predict(scaled_X_test)
y_pred_SGD = model_SGD.predict(scaled_X_test)
y_pred_OLS[:5]

array([16.5653963 , 21.18822792, 21.55107058, 10.88923816, 22.20231988])

In [54]:
y_pred_SGD[:5]

array([16.5869227 , 20.81263699, 21.10425391, 11.31371947, 21.40229997])

In [55]:
y_test[:5].values

array([16.9, 22.4, 21.4,  7.3, 24.7])

In [59]:
mae_OLS = mean_absolute_error(y_test, y_pred_OLS)
mae_SGD = mean_absolute_error(y_test, y_pred_SGD)

mse_OLS = mean_squared_error(y_test, y_pred_OLS)
mse_SGD = mean_squared_error(y_test, y_pred_SGD)

rmse_OLS = np.sqrt(mse_OLS)
rmse_SGD = np.sqrt(mse_SGD)

print(f"{mae_OLS=:.4f} \t\t {mse_OLS=:.4f} \t {rmse_OLS=:.4f}")
print(f"{mae_SGD=:.4f} \t\t {mse_SGD=:.4f} \t {rmse_SGD=:.4f}")

mae_OLS=1.5117 		 mse_OLS=3.7968 	 rmse_OLS=1.9485
mae_SGD=1.5230 		 mse_SGD=4.0822 	 rmse_SGD=2.0205
